version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
      - DB_USER=${DB_USER}
    restart: always

volumes:
  postgres-data:
